const PLACEHOLDER_PROFILE_IMAGE = 'https://picsum.photos/id/40/4106/2806';
const COOKIE_NAME = 'session';
const TOAST_KEY_AUTH = 'auth';
const QUERY_KEY_PRODUCTS = ['products'];
const QUERY_KEY_CATEGORIES = ['categories'];
const TOAST_KEY_ANNOUNCE = 'announcement';
const STANDARD_STALE_TIME = 1 * 60 * 1000;

export {
  COOKIE_NAME,
  PLACEHOLDER_PROFILE_IMAGE,
  QUERY_KEY_CATEGORIES,
  QUERY_KEY_PRODUCTS,
  STANDARD_STALE_TIME,
  TOAST_KEY_ANNOUNCE,
  TOAST_KEY_AUTH
};
